version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://auth_user:auth_password@db:5432/auth_db?sslmode=disable
      - JWT_SECRET=your_jwt_secret_key
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=test@example.com
      - SMTP_PASS=test
      - APP_URL=http://localhost:8080
    depends_on:
      - db
      - mailhog

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
      - POSTGRES_DB=auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP сервер
      - "8025:8025" # Web интерфейс

volumes:
  postgres_data: